name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd Scripts
          chmod 777 install_linux.sh
          sudo ./install_linux.sh

      - name: Build Project | All
        run: bazel build //...

      - name: Run Tests | All
        run: bazel test //...